// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Parse = require("parse");
var Utils$ReactHooksTemplate = require("./Utils.bs.js");

var parse = Parse;

var object_ = parse.Object;

var query = parse.Query;

function createTask(taskName, taskDescription) {
  var task = new Parse.Object("Task");
  task.set("name", taskName);
  task.set("description", taskDescription);
  task.save().then((function (result) {
            return Promise.resolve((console.log(result, "New Task created on the back end"), /* () */0));
          })).catch(Utils$ReactHooksTemplate.logErrorResolve);
  return /* () */0;
}

exports.parse = parse;
exports.object_ = object_;
exports.query = query;
exports.createTask = createTask;
/* parse Not a pure module */
