// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Parse = require("parse");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Timer$ReactHooksTemplate = require("./Timer.bs.js");
var Settings$ReactHooksTemplate = require("./Settings.bs.js");


  require("./styles.css");

;

var parse = Parse;

parse.initialize("CHxKR1K47E6gap2r9Uo5t8MSnX2i7AbjHOGMMqJ5", "9Q7sUPSsJUxijG1yMjoDrlGoRolmJjcYNKcusUJt");

parse.serverURL = "https://parseapi.back4app.com";

function timerFunc(pomodoro, shortBreak, longBreak) {
  return React.createElement(Timer$ReactHooksTemplate.make, {
              pomodoro: pomodoro,
              shortBreak: shortBreak,
              longBreak: longBreak
            });
}

ReactDOMRe.renderToElementWithId(React.createElement(Settings$ReactHooksTemplate.make, {
          timerFunc: timerFunc
        }), "settings");

exports.parse = parse;
exports.timerFunc = timerFunc;
/*  Not a pure module */
