// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Timer$ReactHooksTemplate = require("./Timer.bs.js");
var Settings$ReactHooksTemplate = require("./Settings.bs.js");


  require("./styles.css");

;

ReactDOMRe.renderToElementWithId(React.createElement(Settings$ReactHooksTemplate.make, { }), "settings");

ReactDOMRe.renderToElementWithId(React.createElement(Timer$ReactHooksTemplate.make, { }), "timer");

/*  Not a pure module */
