// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Timer$ReactHooksTemplate = require("./Timer.bs.js");
var Settings$ReactHooksTemplate = require("./Settings.bs.js");


  require("./styles.css");

;

function timerFunc(pomodoro, shortBreak, longBreak) {
  return React.createElement(Timer$ReactHooksTemplate.make, {
              pomodoro: pomodoro,
              shortBreak: shortBreak,
              longBreak: longBreak
            });
}

ReactDOMRe.renderToElementWithId(React.createElement(Settings$ReactHooksTemplate.make, {
          timerFunc: timerFunc
        }), "settings");

exports.timerFunc = timerFunc;
/*  Not a pure module */
