// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Settings(Props) {
  React.useReducer((function (state, action) {
          if (action) {
            var time = action[1];
            switch (action[0]) {
              case 0 : 
                  return /* record */[
                          /* pomodoroTime */time,
                          /* shortBreakTime */state[/* shortBreakTime */1],
                          /* longBreakTime */state[/* longBreakTime */2]
                        ];
              case 1 : 
                  return /* record */[
                          /* pomodoroTime */state[/* pomodoroTime */0],
                          /* shortBreakTime */time,
                          /* longBreakTime */state[/* longBreakTime */2]
                        ];
              case 2 : 
                  return /* record */[
                          /* pomodoroTime */state[/* pomodoroTime */0],
                          /* shortBreakTime */state[/* shortBreakTime */1],
                          /* longBreakTime */time
                        ];
              
            }
          } else {
            return state;
          }
        }), /* record */[
        /* pomodoroTime */1500,
        /* shortBreakTime */300,
        /* longBreakTime */900
      ]);
  return React.createElement("div", {
              className: "row"
            }, React.createElement("div", {
                  className: "col-12 text-center"
                }, React.createElement("h2", undefined, "Options"), React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "col-12"
                        }))));
}

var make = Settings;

exports.make = make;
/* react Not a pure module */
