// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Settings(Props) {
  React.useReducer((function (state, action) {
          return state;
        }), /* record */[
        /* pomodoroTime */1500,
        /* shortBreakTime */300,
        /* longBreakTime */900
      ]);
  return React.createElement("div", {
              className: "row"
            }, React.createElement("div", {
                  className: "col-12 text-center"
                }, React.createElement("h2", undefined, "Options"), React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "col-12"
                        }))));
}

var make = Settings;

exports.make = make;
/* react Not a pure module */
