// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Timer(Props) {
  React.useReducer((function (state, action) {
          switch (action) {
            case 0 : 
                return /* record */[
                        /* running */state[/* running */0],
                        /* pomodoroState : Pomodoro */0
                      ];
            case 1 : 
                return /* record */[
                        /* running */state[/* running */0],
                        /* pomodoroState : ShortBreak */1
                      ];
            case 2 : 
                return /* record */[
                        /* running */state[/* running */0],
                        /* pomodoroState : LongBreak */2
                      ];
            
          }
        }), /* record */[
        /* running */false,
        /* pomodoroState : Pomodoro */0
      ]);
  return React.createElement("div", {
              className: "row"
            }, React.createElement("div", {
                  className: "col-12"
                }), React.createElement("div", {
                  className: "col-12"
                }), React.createElement("div", {
                  className: "col-12"
                }, "Timer Buttons", React.createElement("div", {
                      className: "btn-group"
                    })));
}

var make = Timer;

exports.make = make;
/* react Not a pure module */
