// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function updateWindowTitle(windowTitle) {
  var __x = window.document;
  __x.title = windowTitle;
  return /* () */0;
}

exports.updateWindowTitle = updateWindowTitle;
/* No side effect */
