// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function updateWindowTitle(windowTitle) {
  var __x = window.document;
  __x.title = windowTitle;
  return /* () */0;
}

var listToReactArray = $$Array.of_list;

function rStr(string) {
  return string;
}

exports.updateWindowTitle = updateWindowTitle;
exports.listToReactArray = listToReactArray;
exports.rStr = rStr;
/* No side effect */
